export class Feast {
	day: number;
	month: number;
	order: number;
	forefeast: number | null;
	afterfeast: number | null;
	apdosis: number | null;
	feast: number | null;
	rank: string | null;
	type: string | null;
	name: string;

	constructor(day: number, month: number, order: number, forefeast: number|null, afterfeast: number|null, apdosis: number|null, feast: number|null, rank: string|null, type: string|null, name: string) {
	    this.day = day;
	    this.month = month;
	    this.order = order;
	    this.forefeast = forefeast;
	    this.afterfeast = afterfeast;
	    this.apdosis = apdosis;
	    this.feast = feast;
	    this.rank = rank;
	    this.type = type;
	    this.name = name;
	}
};

let feasts: Feast[] = [
	new Feast( 1, 1, 10, null, null, null, null, "v", "PAN", "Obrezanie podľa tela nášho Pána, Boha a Spasiteľa Ježiša Krista" ),
	new Feast( 1, 1, 20, null, null, null, null, null, "SVATITEL", "Pamiatka nášho otca svätého Bazila Veľkého, arcibiskupa kapadóckej Cézarey" ),
	new Feast( 2, 1, 10, null, null, null, 4, "m", "SVATITEL", "Náš svätý otec Silvester, rímsky pápež" ),
	new Feast( 3, 1, 10, null, null, null, 3, null, "PROROK", "Svätý prorok Malachiáš" ),
	new Feast( 3, 1, 20, null, null, null, 3, null, "MUCENIK", "Svätý mučeník Gordios" ),
	new Feast( 4, 1, 10, null, null, null, 2, null, "APOSTOLI", "Zbor svätých sedemdesiatich apoštolov" ),
	new Feast( 4, 1, 20, null, null, null, 2, null, "PREPODOBNY", "Náš prepodobný otec Teoktist, igumen zo sicílskeho Kukuma" ),
	new Feast( 5, 1, 10, null, null, null, 1, null, "MUCENICI", "Svätí mučeníci Teopempt a Teónas" ),
	new Feast( 5, 1, 20, null, null, null, 1, null, "PREPODOBNA", "Prepodobná Synkletika" ),
	new Feast( 6, 1, 10, 4, 7, 8, 0, "v", "PAN", "Sväté Bohozjavenie nášho Pána, Boha a Spasiteľa Ježiša Krista" ),
	new Feast( 7, 1, 10, null, null, null, -1, "ms", "JAN", "Zhromaždenie k svätému a slávnemu Pánovmu prorokovi, predchodcovi a krstiteľovi Jánovi" ),
	new Feast( 8, 1, 10, null, null, null, -2, null, "PREPODOBNY", "Náš prepodobný otec Juraj Chozebita" ),
	new Feast( 8, 1, 20, null, null, null, -2, null, "PREPODOBNY", "Prepodobný Emilián Vyznávač" ),
	new Feast( 8, 1, 30, null, null, null, -2, null, "PREPODOBNA", "Naša prepodobná matka Dominika" ),
	new Feast( 9, 1, 10, null, null, null, -3, null, "MUCENIK", "Svätý mučeník Polyeukt" ),
	new Feast( 10, 1, 10, null, null, null, -4, null, "SVATITEL", "Náš otec svätý Gregor, nysský biskup" ),
	new Feast( 10, 1, 20, null, null, null, -4, null, "PREPODOBNY", "Prepodobný Domicián, meliténsky biskup" ),
	new Feast( 10, 1, 30, null, null, null, -4, null, "PREPODOBNY", "Náš prepodobný otec Marcián, presbyter a ekonóm Veľkej cirkvi" ),
	new Feast( 11, 1, 10, null, null, null, -5, "s", "PREPODOBNY", "Náš prepodobný otec Teodóz, vodca mníchov spoločného života" ),
	new Feast( 12, 1, 10, null, null, null, -6, null, "MUCENICA", "Svätá mučenica Tatiana" ),
	new Feast( 13, 1, 10, null, null, null, -7, null, "MUCENICI", "Svätí mučeníci Hermyl a Stratonik" ),
	new Feast( 14, 1, 10, null, null, null, -8, null, "PREPODOBNI", "Naši prepodobní otcovia, ktorí boli zavraždení na vrchu Sinaj a na púšti Raita" ),
	new Feast( 14, 1, 20, null, null, null, -8, null, null, "Pamiatkaodchodu do večnosti svätej apoštolom rovnej Niny, osvietiteľky Gruzínska" ),
	new Feast( 15, 1, 10, null, null, null, null, "m", "PREPODOBNI", "Naši prepodobní otcovia Pavol Tébsky a Ján Chatrčník" ),
	new Feast( 16, 1, 10, null, null, null, null, "m", "APOSTOL", "Poklona úctyhodným reťaziam svätého a všechválneho apoštola Petra" ),
	new Feast( 17, 1, 10, null, null, null, null, "ss", "PREPODOBNY", "Náš prepodobný a bohonositeľský otec Anton Veľký" ),
	new Feast( 18, 1, 10, null, null, null, null, "m", "SVATITELIA", "Naši otcovia svätý Atanáz a svätý Cyril, alexandrijskí arcibiskupi" ),
	new Feast( 19, 1, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Makarios Egyptský" ),
	new Feast( 20, 1, 10, null, null, null, null, "ss", "PREPODOBNY", "Náš prepodobný a bohonositeľský otec Eutymios Veľký" ),
	new Feast( 21, 1, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Maxim Vyznávač" ),
	new Feast( 21, 1, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Neofyt" ),
	new Feast( 21, 1, 30, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Eugen, Kandidus, Valerián a Akvila" ),
	new Feast( 22, 1, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Timotej" ),
	new Feast( 22, 1, 20, null, null, null, null, null, "PREPODOBNOMUCENIK", "Svätý prepodobný mučeník Anastáz Perzský" ),
	new Feast( 23, 1, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Klement, ankyrský biskup" ),
	new Feast( 23, 1, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Agatangel" ),
	new Feast( 24, 1, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Xénia Rímska" ),
	new Feast( 25, 1, 10, null, null, null, null, "s", "SVATITEL", "Náš otec svätý Gregor Teológ, konštantínopolský arcibiskup" ),
	new Feast( 26, 1, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Xenofont, jeho manželka Mária a synovia" ),
	new Feast( 27, 1, 10, null, null, null, null, "s", null, "Prenesenieúctyhodných pozostatkov nášho otca svätého Jána Zlatoústeho" ),
	new Feast( 28, 1, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Efrém Sýrsky" ),
	new Feast( 29, 1, 10, null, null, null, null, "m", "HIEROMUCENIK", "Prenesenie pozostatkov svätého hieromučeníka Ignáca Bohonositeľa" ),
	new Feast( 30, 1, 10, null, null, null, null, "ss", "SVATITELIA", "Traja sv. svätitelia, veľkí veľkňazi Bazil Veľký, Gregor Teológ a Ján Zlatoústy" ),
	new Feast( 31, 1, 10, null, null, null, null, "m", "DIVOTVORCOVIA", "Svätí divotvorcovia a nezištníci Kýros a Ján" ),
	new Feast( 1, 2, 10, null, null, null, 1, "m", "MUCENIK", "Svätý mučeník Tryfón" ),
	new Feast( 2, 2, 10, 1, 6, 7, 0, "v", "PAN", "Stretnutie nášho Pána, Boha a Spasiteľa Ježiša Krista" ),
	new Feast( 3, 2, 10, null, null, null, -1, "m", null, "Svätý a spravodlivý Simeon Bohopríjemca a prorokyňa Anna" ),
	new Feast( 4, 2, 10, null, null, null, -2, null, "PREPODOBNY", "Náš prepodobný otec Izidor Peluzijský" ),
	new Feast( 5, 2, 10, null, null, null, -3, null, "MUCENICA", "Svätá mučenica Agáta" ),
	new Feast( 6, 2, 10, null, null, null, -4, null, "PREPODOBNY", "Náš prepodobný otec Bukol, smyrniansky biskup" ),
	new Feast( 7, 2, 10, null, null, null, -5, null, "PREPODOBNY", "Náš prepodobný otec Partenios, lampsacký biskup" ),
	new Feast( 8, 2, 10, null, null, null, -6, "m", "MUCENIK", "Svätý veľkomučeník Teodor Stratilat" ),
	new Feast( 8, 2, 20, null, null, null, -6, null, "PROROK", "Svätý prorok Zachariáš, ktorý videl kosák" ),
	new Feast( 9, 2, 10, null, null, null, -7, null, "MUCENIK", "Svätý mučeník Nikefor" ),
	new Feast( 10, 2, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Charalampés" ),
	new Feast( 11, 2, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Blažej, sebastejský biskup" ),
	new Feast( 12, 2, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Meletios, antiochijský arcibiskup" ),
	new Feast( 13, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Martinián" ),
	new Feast( 14, 2, 10, null, null, null, null, "s", "PREPODOBNY", "Odchod do večnosti nášho prepodobného otca Konštantína Filozofa, mníšskym menom Cyrila, učiteľa Slovanov" ),
	new Feast( 14, 2, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Auxencius" ),
	new Feast( 14, 2, 30, null, null, null, null, null, "PREPODOBNY", "Prepodobný Marón Pustovník, divotvorca" ),
	new Feast( 15, 2, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Onezim" ),
	new Feast( 16, 2, 10, null, null, null, null, "m", "MUCENICI", "Svätí mučeníci kňaz Pamfil, Porfyrios a ich spoločníci" ),
	new Feast( 17, 2, 10, null, null, null, null, null, "MUCENIK", "Svätý veľkomučeník Teodor Tirón" ),
	new Feast( 18, 2, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Lev, rímsky pápež" ),
	new Feast( 19, 2, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Archippos" ),
	new Feast( 20, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Lev, katánijský biskup" ),
	new Feast( 21, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Timotej zo Symbolov" ),
	new Feast( 21, 2, 20, null, null, null, null, null, "SVATITEL", "Náš otec svätý Eustatios, arcibiskup veľkej Antiochie" ),
	new Feast( 22, 2, 10, null, null, null, null, null, "MUCENICI", "Nájdenie úctyhodných pozostatkov svätých mučeníkov v Eugeniu" ),
	new Feast( 23, 2, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Polykarp, smyrniansky biskup" ),
	new Feast( 24, 2, 10, null, null, null, null, "s", "JAN", "Prvé a druhé nájdenie úctyhodnej hlavy svätého a slávneho Pánovho proroka, predchodcu a krstiteľa Jána" ),
	new Feast( 25, 2, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Taras, konštantínopolský arcibiskup" ),
	new Feast( 26, 2, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Porfyrios, gazský biskup" ),
	new Feast( 27, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Prokop Dekapolita" ),
	new Feast( 28, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Bazil, Prokopov spoluaskéta" ),
	new Feast( 29, 2, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Kassián" ),
	new Feast( 1, 3, 10, null, null, null, null, null, "PREPODOBNOMUCENICA", "Svätá prepodobná mučenica Eudokia" ),
	new Feast( 1, 3, 20, null, null, null, null, null, null, "Spomienkaúctyhodných pôstnikov" ),
	new Feast( 2, 3, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Teodot, kerynejský biskup" ),
	new Feast( 3, 3, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Eutropios a jeho spoločníci Kleonik a Bazilisk" ),
	new Feast( 4, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Gerasim od Jordána" ),
	new Feast( 5, 3, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Konón" ),
	new Feast( 6, 3, 10, null, null, null, null, null, "MUCENICI", "Štyridsiati dvaja svätí mučeníci z Amoria" ),
	new Feast( 7, 3, 10, null, null, null, null, null, "HIEROMUCENICI", "Svätí hieromučeníci, ktorí boli biskupi v Chersone: Bazil, Efrém, Kapitón, Eugen, Aiterios a ďalší" ),
	new Feast( 8, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Teofylakt, nikomédijský biskup" ),
	new Feast( 9, 3, 10, null, null, null, null, "s", "MUCENICI", "Štyridsiati svätí mučeníci zo Sebastey" ),
	new Feast( 10, 3, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Kodrat a spoločníci" ),
	new Feast( 11, 3, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Sofronios, jeruzalemský patriarcha" ),
	new Feast( 12, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Teofan Sigrianský" ),
	new Feast( 12, 3, 20, null, null, null, null, null, "SVATITEL", "Náš otec svätý Gregor Dialogos, rímsky pápež" ),
	new Feast( 13, 3, 10, null, null, null, null, null, "SVATITEL", "Prenesenie pozostatkov nášho otca svätého Nikefora, konštantínopolského patriarchu" ),
	new Feast( 14, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Benedikt" ),
	new Feast( 15, 3, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Agapios a s ním ďalší šiesti mučeníci" ),
	new Feast( 16, 3, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Sabinus a Papas" ),
	new Feast( 17, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Alexej, Boží človek" ),
	new Feast( 18, 3, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Cyril, jeruzalemský arcibiskup" ),
	new Feast( 19, 3, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Chryzant a Dária" ),
	new Feast( 20, 3, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia, ktorých Saracéni pozabíjali v kláštore svätého Sávu" ),
	new Feast( 21, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Jakub Vyznávač, katánijský biskup" ),
	new Feast( 22, 3, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Bazil, ankyrský presbyter" ),
	new Feast( 23, 3, 10, null, null, null, null, null, "PREPODOBNOMUCENIK", "Svätý prepodobný mučeník Nikón a jeho učeníci, ktorí boli s ním umučení" ),
	new Feast( 24, 3, 10, null, null, null, 1, null, "PREPODOBNY", "Náš prepodobný otec Zachariáš" ),
	new Feast( 24, 3, 20, null, null, null, 1, null, "SVATITEL", "Náš otec svätý Artemón, biskup pizídijskej Seleucie" ),
	new Feast( 25, 3, 10, 1, null, null, 0, "v", "BOHORODICKA", "Zvestovanie našej presvätej Vládkyni, Bohorodičke Márii, vždy Panne" ),
	new Feast( 26, 3, 10, null, null, null, null, "ms", "BEZTELESNI", "Zhromaždenie k archanjelovi Gabrielovi" ),
	new Feast( 27, 3, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Matróna zo Solúna" ),
	new Feast( 28, 3, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Hilarión Nový a Štefan Divotvorca" ),
	new Feast( 29, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Marek, aretúzsky biskup, a Cyril, diakon" ),
	new Feast( 30, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján, autor spisu Rebrík" ),
	new Feast( 31, 3, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Hypatios, gangriansky biskup" ),
	new Feast( 1, 4, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Mária Egyptská" ),
	new Feast( 2, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Títus Divotvorca" ),
	new Feast( 3, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Nikita, igumen Médikiovho kláštora" ),
	new Feast( 4, 4, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Jozef Hymnograf a Juraja z Maley" ),
	new Feast( 5, 4, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Teodul, Agatopod a spoločníci" ),
	new Feast( 6, 4, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Eutychios, konštantínopolský arcibiskup" ),
	new Feast( 6, 4, 20, null, null, null, null, "s", null, "Odchoddo večnosti nášho otca svätého Metoda, učiteľa Slovanov" ),
	new Feast( 7, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Juraj, mytilénsky biskup" ),
	new Feast( 8, 4, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Herodión, Agabus, Rúfus, Asynkrit, Flegont a Hermés" ),
	new Feast( 9, 4, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Eupsychios" ),
	new Feast( 10, 4, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Terencius, Pompejus a spoločníci" ),
	new Feast( 11, 4, 10, null, null, null, null, "m", "HIEROMUCENIK", "Svätý hieromučeník Antipas, biskup ázijského Pergama" ),
	new Feast( 12, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Bazil, parijský biskup" ),
	new Feast( 13, 4, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Artemón a spoločníci" ),
	new Feast( 14, 4, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Martin Vyznávač, rímsky pápež" ),
	new Feast( 15, 4, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Aristarch, Pudent a Trofim" ),
	new Feast( 16, 4, 10, null, null, null, null, null, "MUCENICE", "Sväté mučenice a panny Agapa, Irena a Chionia" ),
	new Feast( 17, 4, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Simeon z Perzie a Akakios, meliténsky biskup" ),
	new Feast( 18, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján, učeník svätého Gregora Dekapolitu" ),
	new Feast( 19, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján zo Starej Lavry" ),
	new Feast( 20, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Teodor Trichinas" ),
	new Feast( 21, 4, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Január a spoločníci" ),
	new Feast( 21, 4, 20, null, null, null, null, null, "HIEROMUCENICI", "Svätý hieromučeník Teodor z Pergy" ),
	new Feast( 22, 4, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Teodor Sykeónsky" ),
	new Feast( 23, 4, 10, null, null, null, null, "ss", "MUCENIK", "Svätý a slávny veľkomučeník, triumfátor a divotvorca Juraj" ),
	new Feast( 24, 4, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Sáva Stratilat" ),
	new Feast( 25, 4, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol a evanjelista Marek" ),
	new Feast( 26, 4, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Bazil, amázijský biskup" ),
	new Feast( 27, 4, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Simeon, Pánov príbuzný" ),
	new Feast( 27, 4, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Štefan" ),
	new Feast( 28, 4, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Jasón a Sósipatros" ),
	new Feast( 28, 4, 20, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Dadas, Maxim a Kvintilián." ),
	new Feast( 29, 4, 10, null, null, null, null, null, "MUCENICI", "Deviati svätí mučeníci z Kyzika" ),
	new Feast( 29, 4, 20, null, null, null, null, null, "PREPODOBNY", "Prepodobný Memnón Divotvorca" ),
	new Feast( 30, 4, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol Jakub, brat svätého Jána Teológa" ),
	new Feast( 1, 5, 10, null, null, null, null, null, "PROROK", "Svätý prorok Jeremiáš" ),
	new Feast( 2, 5, 10, null, null, null, null, "m", "SVATITEL", "Náš otec svätý Atanáz Veľký" ),
	new Feast( 3, 5, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Timotej a Maura" ),
	new Feast( 3, 5, 20, null, null, null, null, "s", null, "Odchoddo večnosti nášho prepodobného otca Teodóza, igumena Pečerského monastiera" ),
	new Feast( 4, 5, 10, null, null, null, null, null, "MUCENICA", "Svätá mučenica Pelágia" ),
	new Feast( 5, 5, 10, null, null, null, null, null, "MUCENICA", "Svätá a slávna mučenica Irena" ),
	new Feast( 6, 5, 10, null, null, null, null, null, null, "Svätý spravodlivý a veľmi trpezlivý Jób" ),
	new Feast( 7, 5, 10, null, null, null, null, "m", null, "Spomienkana znamenie úctyhodného kríža, ktoré sa ukázalo na nebi vo svätého meste Jeruzaleme" ),
	new Feast( 8, 5, 10, null, null, null, null, "ss", "APOSTOL", "Svätý apoštol a evanjelista Ján Teológ, milovaný učeník, ktorý ležal na Kristovej hrudi, panic" ),
	new Feast( 8, 5, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Arsenios Veľký" ),
	new Feast( 9, 5, 10, null, null, null, null, null, "PROROK", "Svätý prorok Izaiáš" ),
	new Feast( 9, 5, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Christofor" ),
	new Feast( 9, 5, 30, null, null, null, null, "s", null, "Prenesenieúctyhodných pozostatkov nášho otca svätého Mikuláša Divotvorcu z Myry do mesta Bari" ),
	new Feast( 10, 5, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol Šimon Horlivec" ),
	new Feast( 11, 5, 10, null, null, null, null, "ss", "HIEROMUCENIK", "Blažený hieromučeník Vasiľ Hopko, prešovský svätiaci biskup" ),
	new Feast( 11, 5, 20, null, null, null, null, null, null, "Založenie Konštantínopola" ),
	new Feast( 11, 5, 30, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Mókios" ),
	new Feast( 11, 5, 40, null, null, null, null, "ss", null, "Svätí apoštolom rovní Cyril a Metod, učitelia Slovanov" ),
	new Feast( 12, 5, 10, null, null, null, null, null, "SVATITEL", "Naši otec svätý Epifanios, cyperský biskup" ),
	new Feast( 12, 5, 20, null, null, null, null, null, "SVATITEL", "Naši otec svätý Germanos, konštantínopolský patriarcha" ),
	new Feast( 13, 5, 10, null, null, null, null, null, "MUCENICA", "Svätá mučenica Glykéria" ),
	new Feast( 14, 5, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Izidor" ),
	new Feast( 15, 5, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Pachómios Veľký" ),
	new Feast( 15, 5, 20, null, null, null, null, "ms", "SVATITEL", "Náš otec svätý Izaiáš, biskup a rostovský divotvorca" ),
	new Feast( 16, 5, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Teodor Posvätený, učeník svätého Pachómia Veľkého" ),
	new Feast( 17, 5, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Andronik a spoločníčka Junia" ),
	new Feast( 18, 5, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Teodot z Ankyry" ),
	new Feast( 19, 5, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Patrik, pruský biskup, a spoločníci" ),
	new Feast( 20, 5, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Tallelaios" ),
	new Feast( 21, 5, 10, null, null, null, null, "s", null, "Svätí veľkí králi a apoštolom rovní Konštantín a Helena" ),
	new Feast( 22, 5, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Bazilisk" ),
	new Feast( 23, 5, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Michal, synadský biskup" ),
	new Feast( 23, 5, 20, null, null, null, null, null, "PREPODOBNA", "Prepodobná Eufrozína Polocká" ),
	new Feast( 24, 5, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Simeon z Obdivuhodného vrchu" ),
	new Feast( 24, 5, 20, null, null, null, null, "ms", "PREPODOBNY", "Prepodobný Nikita Stĺpnik, perejaslavský divotvorca" ),
	new Feast( 25, 5, 10, null, null, null, null, "s", "JAN", "Tretie nájdenie úctyhodného hlavy svätého a slávneho Pánovho predchodcu, predchodcu a krstiteľa Jána" ),
	new Feast( 26, 5, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Karpos, jeden zo sedemdesiatich a Alfeus" ),
	new Feast( 27, 5, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Terapont" ),
	new Feast( 28, 5, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Nikita, chalcedónsky biskup" ),
	new Feast( 29, 5, 10, null, null, null, null, null, "PREPODOBNA", "Svätá prepodobná mučenica Teodózia, panna" ),
	new Feast( 30, 5, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Izák, igumen Dalmatovho kláštora" ),
	new Feast( 31, 5, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Hermas" ),
	new Feast( 31, 5, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Hermeias" ),
	new Feast( 1, 6, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Justín Filozof a spoločníci" ),
	new Feast( 2, 6, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Nikefor Vyznávač, konštantínopolský patriarcha" ),
	new Feast( 3, 6, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Lucilián a spoločníci" ),
	new Feast( 4, 6, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Métrofanés, konštantínopolský patriarcha" ),
	new Feast( 5, 6, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Dorotej, týrsky biskup" ),
	new Feast( 5, 6, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Kozma, arménsky presbyter" ),
	new Feast( 6, 6, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Bessarión Divotvorca" ),
	new Feast( 6, 6, 20, null, null, null, null, null, "PREPODOBNY", "Prepodobný Hilarión Nový" ),
	new Feast( 7, 6, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Teodot Ankyrský" ),
	new Feast( 8, 6, 10, null, null, null, null, "m", "MUCENIK", "Prenesenie pozostatkov svätého veľkomučeníka Teodora Tiróna" ),
	new Feast( 9, 6, 10, null, null, null, null, "m", "SVATITEL", "Náš otec svätý Cyril, alexandrijský arcibiskup" ),
	new Feast( 10, 6, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Timotej, pruský biskup" ),
	new Feast( 11, 6, 10, null, null, null, null, "s", "APOSTOLI", "Svätí apoštoli Bartolomej a Barnabáš" ),
	new Feast( 12, 6, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Onufrios Veľký" ),
	new Feast( 12, 6, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Peter Atoský" ),
	new Feast( 13, 6, 10, null, null, null, null, null, "MUCENICA", "Svätá mučenica Akvilína" ),
	new Feast( 13, 6, 20, null, null, null, null, null, "SVATITEL", "Svätý Trifylios, biskup cyperskej Leukosie" ),
	new Feast( 14, 6, 10, null, null, null, null, null, "PROROK", "Svätý prorok Elizeus" ),
	new Feast( 14, 6, 20, null, null, null, null, null, "SVATITEL", "Náš otec svätý Metod, konštantínopolský patriarcha" ),
	new Feast( 15, 6, 10, null, null, null, null, null, "PROROK", "Svätý prorok Amos" ),
	new Feast( 15, 6, 20, null, null, null, null, null, "PREPODOBNY", "Prepodobný Hieronym, stridonský presbyter" ),
	new Feast( 16, 6, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Tychón Divotvorca, amatuntský biskup" ),
	new Feast( 17, 6, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Manuel, Sabel a Izmael" ),
	new Feast( 17, 6, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Hypatios, igumen Rufínovho kláštora" ),
	new Feast( 18, 6, 10, null, null, null, null, null, "MUCENICI", "Svätý mučeník Leontios a s ním mučeníci Hypatios a Teodulos" ),
	new Feast( 19, 6, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol Júda Tadeáš, podľa tela Pánov brat" ),
	new Feast( 20, 6, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Metod, patarský biskup" ),
	new Feast( 21, 6, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Julián Tarzský" ),
	new Feast( 22, 6, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Eusebios, samosatský biskup" ),
	new Feast( 23, 6, 10, null, null, null, null, null, "MUCENICA", "Svätá mučenica Agripína" ),
	new Feast( 24, 6, 10, null, 1, null, 0, "v", "JAN", "Narodenie úctyhodného a slávneho Pánovho proroka, predchodcu a krstiteľa Jána" ),
	new Feast( 25, 6, 10, null, null, null, -1, null, "MUCENICA", "Svätá prepodobná mučenica Febrónia" ),
	new Feast( 26, 6, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Dávid zo Solúna" ),
	new Feast( 27, 6, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Samson Pohostinný" ),
	new Feast( 28, 6, 10, null, null, null, null, "m", "PAN", "Najsladšieho Pána, Boha a Spasiteľa nášho Ježiša Krista, milujúceho ľudí" ),
	new Feast( 28, 6, 20, null, null, null, null, null, null, "Preneseniepozostatkov svätých nezištníkov Kýra a Jána" ),
	new Feast( 29, 6, 10, null, 1, null, 0, "v", "APOSTOLI", "Svätí, slávni a znamenití hlavní apoštoli Peter a Pavol" ),
	new Feast( 30, 6, 10, null, null, null, -1, "ms", "APOSTOLI", "Zbor svätých, slávnych a znamenitých dvanástich apoštolov" ),
	new Feast( 1, 7, 10, null, null, null, null, "m", null, "Svätí nezištníci a divotvorcovia Kozma a Damián" ),
	new Feast( 2, 7, 10, null, null, null, null, "ms", "BOHORODICKA", "Uloženie úctyhodného rúcha našej presvätej Vládkyne a Bohorodičky v Blachernách" ),
	new Feast( 3, 7, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Hyacint" ),
	new Feast( 4, 7, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Andrej Jeruzalemčan" ),
	new Feast( 4, 7, 20, null, null, null, null, null, "PREPODOBNA", "Prepodobná Marta, matka svätého Simeona" ),
	new Feast( 5, 7, 10, null, null, null, null, "ss", null, "Svätí apoštolom rovní Cyril a Metod, učitelia Slovanov" ),
	new Feast( 5, 7, 20, null, null, null, null, "s", "PREPODOBNY", "Náš prepodobný otec Atanáz Atoský" ),
	new Feast( 6, 7, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Sisoés Veľký" ),
	new Feast( 7, 7, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Tomáš z Maley" ),
	new Feast( 7, 7, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Akakios, ktorý sa spomína v spise Rebrík" ),
	new Feast( 8, 7, 10, null, null, null, null, "m", "MUCENIK", "Svätý veľkomučeník Prokop" ),
	new Feast( 9, 7, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Pankrác, tauromenský biskup" ),
	new Feast( 10, 7, 10, null, null, null, null, null, "MUCENICI", "Štyridsiati piati svätí mučeníci z arménskeho Nikopola" ),
	new Feast( 10, 7, 20, null, null, null, null, "s", "PREPODOBNY", "Náš prepodobný otec Anton Pečersko-Kyjevský" ),
	new Feast( 10, 7, 30, null, null, null, null, null, "MUCENICI", "Svätí bratia a mučeníci František, Mútus, Rafael a spoločníci, ktorí boli zabití v Damasku" ),
	new Feast( 11, 7, 10, null, null, null, null, "m", "MUCENICA", "Svätá všechválna mučenica Eufémia" ),
	new Feast( 11, 7, 20, null, null, null, null, null, null, "Odchoddo večnosti blaženej Oľgy, kyjevskej kňažnej, pri svätom krste nazvanej Helena" ),
	new Feast( 12, 7, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Proklos a Hilarios" ),
	new Feast( 12, 7, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Michal Maleinský" ),
	new Feast( 13, 7, 10, null, null, null, null, "m", "BEZTELESNI", "Zhromaždenie k svätému archanjelovi Gabrielovi" ),
	new Feast( 13, 7, 20, null, null, null, null, null, "SVATITEL", "Náš otec svätý Julián, kenomanijský biskup" ),
	new Feast( 14, 7, 10, null, null, null, null, "m", "APOSTOL", "Svätý apoštol Akvila" ),
	new Feast( 15, 7, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Kéryk a jeho matka Julita" ),
	new Feast( 15, 7, 20, null, null, null, null, "ss", null, "Svätý apoštolom rovný a veľký knieža Vladimír, pri svätom krste nazvaný Bazil" ),
	new Feast( 16, 7, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Aténogenés a jeho 10 učeníci" ),
	new Feast( 17, 7, 10, null, null, null, null, "ss", "HIEROMUCENIK", "Hieromučeník blahoslavený Pavol Peter Gojdič, prešovský biskup" ),
	new Feast( 17, 7, 20, null, null, null, null, "m", "MUCENICA", "Svätá veľkomučenica Marína" ),
	new Feast( 18, 7, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Hyacint z Amastridy" ),
	new Feast( 18, 7, 20, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Andrej - Svorad a Beňadik" ),
	new Feast( 19, 7, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Makrína, sestra Bazila Veľkého" ),
	new Feast( 19, 7, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Dios" ),
	new Feast( 20, 7, 10, null, null, null, null, "ss", "PROROK", "Svätý a slávny prorok Eliáš" ),
	new Feast( 21, 7, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Simeon, blázon pre Krista, a Ján, jeho spoluaskéta" ),
	new Feast( 21, 7, 20, null, null, null, null, null, "PROROK", "Prorok Ezechiel" ),
	new Feast( 22, 7, 10, null, null, null, null, "m", null, "Svätá myronosička a apoštolom rovná Mária Magdaléna" ),
	new Feast( 23, 7, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Trofim, Teofil a spoločníci" ),
	new Feast( 24, 7, 10, null, null, null, null, null, "MUCENICA", "Svätá veľkomučenica Kristína" ),
	new Feast( 24, 7, 20, null, null, null, null, "s", "MUCENICI", "Svätí mučeníci Boris a Gleb, pri svätom krste nazvaní Roman a Dávid" ),
	new Feast( 25, 7, 10, null, null, null, null, "s", null, "Zosnutiesvätej Anny, matky presvätej Bohorodičky" ),
	new Feast( 26, 7, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Hermolaos a spoločníci" ),
	new Feast( 26, 7, 20, null, null, null, null, null, "PREPODOBNA", "Svätá prepodobná mučenica Paraskeva" ),
	new Feast( 27, 7, 10, null, null, null, null, "s", "MUCENIK", "Svätý veľkomučeník a uzdravovateľ Panteleimón" ),
	new Feast( 27, 7, 20, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia sedmopočetníci Cyril, Metod, Gorazd, Kliment, Naum, Sáva, Angelár" ),
	new Feast( 28, 7, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli a diakoni Prochor, Nikanor, Timón a Parmenas" ),
	new Feast( 29, 7, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Kallinik" ),
	new Feast( 30, 7, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Silas, Silván a spoločníci" ),
	new Feast( 31, 7, 10, null, null, null, 1, "m", null, "Svätý a spravodlivý Eudokim" ),
	new Feast( 1, 8, 10, 1, null, null, 0, "ms", "PAN", "Vynesenie úctyhodných driev úctyhodného a životodarného Kríža" ),
	new Feast( 1, 8, 20, null, null, null, null, null, "MUCENICI", "Siedmi svätí makabejskí mučeníci, ich matka Solomona a starec Eleazar" ),
	new Feast( 2, 8, 10, null, null, null, null, "m", null, "Preneseniepozostatkov svätého prvomučeníka a archidiakona Štefana" ),
	new Feast( 3, 8, 10, null, null, null, null, null, "PREPODOBNI", "Naši prepodobní otcovia Izák, Dalmat a Faust" ),
	new Feast( 4, 8, 10, null, null, null, null, null, null, "Siedmisvätí mladíci z Efezu" ),
	new Feast( 4, 8, 20, null, null, null, null, null, "PREPODOBNOMUCENICA", "Svätá prepodobná mučenica Eudokia" ),
	new Feast( 5, 8, 10, null, null, null, 1, "m", "MUCENIK", "Svätý mučeník Eusignios" ),
	new Feast( 6, 8, 10, 1, 6, 7, 0, "v", "PAN", "Sväté Premenenie nášho Pána, Boha a Spasiteľa Ježiša Krista" ),
	new Feast( 7, 8, 10, null, null, null, -1, null, "PREPODOBNOMUCENIK", "Svätý prepodobný mučeník Domécius" ),
	new Feast( 8, 8, 10, null, null, null, -2, null, "SVATITEL", "Svätý Emilián Vyznávač, kyzický biskup" ),
	new Feast( 9, 8, 10, null, null, null, -3, "s", "APOSTOL", "Svätý apoštol Matej" ),
	new Feast( 10, 8, 10, null, null, null, -4, null, "MUCENIK", "Svätý mučeník a archidiakon Vavrinec" ),
	new Feast( 11, 8, 10, null, null, null, -5, null, "MUCENIK", "Svätý mučeník Euplos" ),
	new Feast( 12, 8, 10, null, null, null, -6, null, "MUCENICI", "Svätí mučeníci Fótios a Anikét" ),
	new Feast( 13, 8, 10, null, null, null, -7, null, "PREPODOBNY", "Náš prepodobný otec Maxim Vyznávač" ),
	new Feast( 14, 8, 10, null, null, null, 1, "m", "PROROK", "Svätý prorok Micheáš" ),
	new Feast( 14, 8, 20, null, null, null, 1, "s", null, "Prenesenieúctyhodných pozostatkov nášho prepodobného otca Teodóza, pečerského igumena" ),
	new Feast( 15, 8, 10, 1, 7, 8, 0, "v", "BOHORODICKA", "Zosnutie našej presvätej Vládkyne, Bohorodičky Márie, vždy Panny" ),
	new Feast( 16, 8, 10, null, null, null, -1, "ms", null, "PrenesenieRukou neutvoreného obrazu nášho Pána, Boha a Spasiteľa Ježiša Krista, to jest svätého plátna, z Edessy do Konštantínopola" ),
	new Feast( 16, 8, 20, null, null, null, -1, null, "MUCENIK", "Svätý mučeník Diomédes" ),
	new Feast( 17, 8, 10, null, null, null, -2, null, "MUCENIK", "Svätý mučeník Myrón" ),
	new Feast( 18, 8, 10, null, null, null, -3, null, "MUCENICI", "Svätí mučeníci Flórus a Laurus" ),
	new Feast( 19, 8, 10, null, null, null, -4, null, "MUCENIK", "Svätý mučeník Andrej Stratopedarcha a spoločníci" ),
	new Feast( 20, 8, 10, null, null, null, -5, null, "PROROK", "Svätý prorok Samuel" ),
	new Feast( 21, 8, 10, null, null, null, -6, null, "APOSTOL", "Svätý apoštol Tadeáš" ),
	new Feast( 21, 8, 20, null, null, null, -6, null, "MUCENICA", "Svätá mučenica Bassa" ),
	new Feast( 22, 8, 10, null, null, null, -7, null, "MUCENIK", "Svätý mučeník Agatonik a spoločníci" ),
	new Feast( 23, 8, 10, null, null, null, -8, null, "MUCENIK", "Svätý mučeník Lupus" ),
	new Feast( 23, 8, 20, null, null, null, -8, null, "HIEROMUCENIK", "Svätý hieromučeník Irenej, lyonský biskup" ),
	new Feast( 24, 8, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Eutychés" ),
	new Feast( 25, 8, 10, null, null, null, null, "ss", "HIEROMUCENIK", "Hieromučeník blahoslavený Metod Dominik Trčka, michalovský igumen" ),
	new Feast( 25, 8, 20, null, null, null, null, "m", null, "Vrátenie pozostatkov svätého apoštola Bartolomeja" ),
	new Feast( 25, 8, 30, null, null, null, null, null, "APOSTOL", "Svätý apoštol Títus" ),
	new Feast( 26, 8, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Adrián a Natália" ),
	new Feast( 27, 8, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Pimen" ),
	new Feast( 28, 8, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Mojžiš Etiópsky" ),
	new Feast( 28, 8, 20, null, null, null, null, null, "SVATITEL", "Náš otec svätý Augustín, hipponský biskup" ),
	new Feast( 28, 8, 30, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Gebre Michal, etiópsky presbyter" ),
	new Feast( 29, 8, 10, null, 1, null, 0, "v", "JAN", "Sťatie úctyhodného hlavy úctyhodného a slávneho proroka, predchodcu a krstiteľa Jána" ),
	new Feast( 30, 8, 10, null, null, null, -1, null, "SVATITELIA", "Naši otcovia svätý Alexander, svätý Ján a svätý Pavol Nový, konštantínopolskí patriachovia" ),
	new Feast( 31, 8, 10, null, null, null, null, "ms", "BOHORODICKA", "Uloženie úctyhodného pásu našej presvätej Vládkyne a Bohorodičky" ),
	new Feast( 1, 9, 10, null, null, null, null, "s", null, "Začiatok indiktu, to jest nového roka" ),
	new Feast( 1, 9, 20, null, null, null, null, null, "PREPODOBNY", "Pamiatka nášho prepodobného otca Simeona Stĺpnika a jeho matky" ),
	new Feast( 1, 9, 30, null, null, null, null, null, "BOHORODICKA", "Zhromaždenie k presvätej Bohorodičke z Miasén" ),
	new Feast( 2, 9, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Mamant" ),
	new Feast( 2, 9, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján Pôstnik, konštantínopolský patriarcha" ),
	new Feast( 3, 9, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Antim, nikomédijský biskup" ),
	new Feast( 3, 9, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Teoktist" ),
	new Feast( 4, 9, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Babylas, biskup veľkej Antiochie" ),
	new Feast( 4, 9, 20, null, null, null, null, null, "PROROK", "Svätý prorok Mojžiš, ktorý videl Boha" ),
	new Feast( 5, 9, 10, null, null, null, null, "m", "PROROK", "Svätý prorok Zachariáš, otec úctyhodného Jána Predchodcu" ),
	new Feast( 6, 9, 10, null, null, null, null, "m", "BEZTELESNI", "Spomienka na zázrak, ktorý vykonal veľvojvodca Michal v Kolosách" ),
	new Feast( 7, 9, 10, null, null, null, 1, "m", "MUCENIK", "Svätý mučeník Sózont" ),
	new Feast( 8, 9, 10, 1, 3, 4, 0, "v", "BOHORODICKA", "Narodenie našej presvätej Vládkyne, Bohorodičky Márie, vždy Panny" ),
	new Feast( 9, 9, 10, null, null, null, -1, "m", null, "Svätí a spravodliví Boží predkovia Joachim a Anna" ),
	new Feast( 10, 9, 10, null, null, null, -2, null, "MUCENICE", "Sväté mučenice Ménodora, Métrodora a Nymfodora" ),
	new Feast( 11, 9, 10, null, null, null, -3, null, "PREPODOBNA", "Naša prepodobná matka Teodora Alexandrijská" ),
	new Feast( 12, 9, 10, null, null, null, -4, null, "HIEROMUCENIK", "Svätý hieromučeník Autonomos" ),
	new Feast( 13, 9, 10, null, null, null, 1, "ms", null, "Pamiatkazaloženia chrámu svätého vzkriesenia Krista a nášho Boha" ),
	new Feast( 14, 9, 10, 1, 6, 7, 0, "v", "PAN", "Povýšenie úctyhodného a životodarného Kríža nad celým svetom" ),
	new Feast( 15, 9, 10, null, null, null, -1, "s", "BOHORODICKA", "Presvätá Bohorodička Spolutrpiteľka" ),
	new Feast( 15, 9, 20, null, null, null, -1, "m", "MUCENIK", "Svätý veľkomučeník Nikita" ),
	new Feast( 16, 9, 10, null, null, null, -2, "m", "MUCENICA", "Svätá všechválna veľkomučenica Eufémia" ),
	new Feast( 17, 9, 10, null, null, null, -3, null, "MUCENICA", "Svätá mučenica Sofia a jej tri dcéry Viera, Nádej a Láska" ),
	new Feast( 18, 9, 10, null, null, null, -4, null, "PREPODOBNY", "Náš prepodobný otec Eumenios Divotvorca, gortynský biskup" ),
	new Feast( 19, 9, 10, null, null, null, -5, null, "MUCENICI", "Svätí mučeníci Trofim, Sabbatios a Dorymedont" ),
	new Feast( 20, 9, 10, null, null, null, -6, "m", "MUCENIK", "Svätý veľkomučeník Eustatios a spoločníci" ),
	new Feast( 20, 9, 20, null, null, null, -6, "ms", null, "Svätý mučeník a vyznávač, veľký knieža Michal a jeho bojar Teodor, černigovskí divotvorcovia" ),
	new Feast( 21, 9, 10, null, null, null, -7, null, "APOSTOL", "Svätý apoštol Kodrat z Magnézie" ),
	new Feast( 22, 9, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Fókas, sinopský biskup" ),
	new Feast( 23, 9, 10, null, null, null, null, "ms", "JAN", "Počatie úctyhodného a slávneho proroka, predchodcu a krstiteľa Jána" ),
	new Feast( 24, 9, 10, null, null, null, null, "m", "MUCENICA", "Svätá prvomučenica a apoštolom rovná Tekla" ),
	new Feast( 25, 9, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Eufrozína" ),
	new Feast( 26, 9, 10, null, null, null, null, "ss", null, "Odchoddo večnosti svätého apoštola a evanjelistu Jána Teológa" ),
	new Feast( 27, 9, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Kallistrat a jeho spoločníci" ),
	new Feast( 27, 9, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Níl" ),
	new Feast( 28, 9, 10, null, null, null, null, "s", "PREPODOBNY", "Náš prepodobný otec a vyznávač Charitón" ),
	new Feast( 28, 9, 20, null, null, null, null, null, "SVATITEL", "Svätý Václav, české knieža" ),
	new Feast( 29, 9, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Kyriak Pustovník" ),
	new Feast( 30, 9, 10, null, null, null, null, "m", "HIEROMUCENIK", "Svätý hieromučeník Gregor, biskup Veľkého Arménska" ),
	new Feast( 1, 10, 10, null, null, null, null, "v", "BOHORODICKA", "Presvätá Bohorodička Och null, rankyňa" ),
	new Feast( 1, 10, 20, null, null, null, null, null, "APOSTOL", "Svätý apoštol Ananiáš, jeden zo sedemdesiatich" ),
	new Feast( 1, 10, 30, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Roman Sladkopevec" ),
	new Feast( 2, 10, 10, null, null, null, null, "m", "HIEROMUCENIK", "Svätý hieromučeník Cyprián" ),
	new Feast( 2, 10, 20, null, null, null, null, null, "MUCENICA", "Svätá mučenica Justína" ),
	new Feast( 2, 10, 30, null, null, null, null, null, "BLAZON", "Svätý Andrej, blázon pre Krista" ),
	new Feast( 3, 10, 10, null, null, null, null, "m", "HIEROMUCENIK", "Svätý hieromučeník Dionýz Areopagita" ),
	new Feast( 4, 10, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Hierotej, aténsky biskup" ),
	new Feast( 4, 10, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec František Assiský" ),
	new Feast( 5, 10, 10, null, null, null, null, null, "MUCENICA", "Svätá mučenica Charitína" ),
	new Feast( 6, 10, 10, null, null, null, null, "s", "APOSTOL", "Svätý a slávny apoštol Tomáš" ),
	new Feast( 7, 10, 10, null, null, null, null, "m", "MUCENICI", "Svätí mučeníci Sergej a Bakchus" ),
	new Feast( 8, 10, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Pelágia" ),
	new Feast( 9, 10, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol Jakub Alfejov" ),
	new Feast( 10, 10, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Eulampios a Eulampia" ),
	new Feast( 11, 10, 10, null, null, null, null, null, "APOSTOL", "Svätý apoštol Filip, jeden zo siedmich diakonov" ),
	new Feast( 12, 10, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Probus, Tarach a Andronik" ),
	new Feast( 12, 10, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Kozma Jeruzalemčan" ),
	new Feast( 13, 10, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Karpos, Papyl a Agatonika" ),
	new Feast( 14, 10, 10, null, null, null, null, "m", "MUCENICI", "Svätí mučeníci Nazarios, Gerbasios, Protasios a Celzius" ),
	new Feast( 14, 10, 20, null, null, null, null, "m", "PREPODOBNA", "Naša prepodobná matka Paraskeva Trnovská" ),
	new Feast( 15, 10, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Eutymios Nový" ),
	new Feast( 15, 10, 20, null, null, null, null, null, "PREPODOBNOMUCENIK", "Svätý prepodobný mučeník Lukián, presbyter veľkej Antiochie" ),
	new Feast( 16, 10, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Longín Stotník" ),
	new Feast( 17, 10, 10, null, null, null, null, null, "PROROK", "Svätý prorok Ozeáš" ),
	new Feast( 17, 10, 20, null, null, null, null, null, "PREPODOBNOMUCENIK", "Svätý prepodobný mučeník Andrej Krétsky" ),
	new Feast( 18, 10, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol a evanjelista Lukáš" ),
	new Feast( 19, 10, 10, null, null, null, null, null, "PROROK", "Svätý prorok Joel" ),
	new Feast( 19, 10, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Varus" ),
	new Feast( 19, 10, 30, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján Rilský" ),
	new Feast( 20, 10, 10, null, null, null, null, "m", "MUCENIK", "Svätý veľkomučeník Artemios" ),
	new Feast( 21, 10, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Hilarión Veľký" ),
	new Feast( 22, 10, 10, null, null, null, null, null, null, "Svätý apoštolom rovný Aberkios Divotvorca, hierapolský biskup" ),
	new Feast( 23, 10, 10, null, null, null, null, "ms", "APOSTOL", "Svätý apoštol Jakub, podľa tela Pánov brat" ),
	new Feast( 24, 10, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Aretas a spoločníci" ),
	new Feast( 25, 10, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci a notári Marcián a Martyrios" ),
	new Feast( 26, 10, 10, null, null, null, null, "ss", "MUCENIK", "Svätý a slávny veľkomučeník Demeter Myromvonný" ),
	new Feast( 26, 10, 20, null, null, null, null, null, null, "Spomienkana veľké a hrozné zemetrasenie" ),
	new Feast( 27, 10, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Nestor" ),
	new Feast( 27, 10, 20, null, null, null, null, null, "MUCENICA", "Svätá mučenica Kapitolína a jej otrokyňa Eroteida" ),
	new Feast( 28, 10, 10, null, null, null, null, null, "MUCENIK", "Svätí mučeník Terencius a Neonilla" ),
	new Feast( 28, 10, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a tvorca kánonov Štefan Svätosávsky" ),
	new Feast( 28, 10, 30, null, null, null, null, "ms", "MUCENICA", "Svätá mučenica Paraskeva z Ikónia" ),
	new Feast( 29, 10, 10, null, null, null, null, null, "PREPODOBNA", "Svätá prepodobná mučenica Anastázia" ),
	new Feast( 29, 10, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Abramios Zatvárateľ" ),
	new Feast( 29, 10, 30, null, null, null, null, "ms", null, "Odchoddo večnosti nášho prepodobného otca Abramia Archimandritu, rostovského divotvorcu" ),
	new Feast( 30, 10, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Zénobios a jeho sestra Zénobia" ),
	new Feast( 31, 10, 10, null, null, null, null, "ss", "HIEROMUCENIK", "Blahoslavený Teodor Romža, mukačevský biskup a mučeník" ),
	new Feast( 31, 10, 20, null, null, null, null, null, "APOSTOL", "Svätí apoštoli Stachys, Amplias a spoločníci" ),
	new Feast( 31, 10, 30, null, null, null, null, null, "MUCENIK", "Svätý mučeník Epimach" ),
	new Feast( 1, 11, 10, null, null, null, null, "m", null, "Svätí divotvorcovia a nezištníci Kozma a Damián" ),
	new Feast( 2, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Akindyn, Pegasios, Aftonios, Elpidéfor a Anempodist" ),
	new Feast( 3, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci biskup Akepsimas, presbyter Jozef a diakon Aitalas" ),
	new Feast( 3, 11, 20, null, null, null, null, null, null, "Založenie chrámu svätého veľkomučeníka Juraja v Lydde, kde je uložené jeho úctyhodné telo" ),
	new Feast( 4, 11, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Joannikios Veľký" ),
	new Feast( 4, 11, 20, null, null, null, null, null, "HIEROMUCENICI", "Svätý mučeník Nikander, myrský biskup, a Hermaios, presbyter" ),
	new Feast( 5, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Galaktión a Epistéma" ),
	new Feast( 6, 11, 10, null, null, null, null, "m", "SVATITEL", "Náš otec svätý Pavol Vyznávač, konštantínopolský arcibiskup" ),
	new Feast( 7, 11, 10, null, null, null, null, null, "MUCENICI", "Tridsiati traja svätí mučeníci z Melitíny" ),
	new Feast( 7, 11, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Lazár Divotvorca, ktorý sa postil na vrchu Galésion" ),
	new Feast( 8, 11, 10, null, null, null, null, "ss", "BEZTELESNI", "Zhromaždenie k veľvojvodcovi Michalovi a ďalším beztelesným silám" ),
	new Feast( 9, 11, 10, null, null, null, null, null, "PREPODOBNA", "Naša prepodobná matka Matróna" ),
	new Feast( 9, 11, 20, null, null, null, null, null, "PREPODOBNA", "Prepodobná Teoktista z ostrova Lesbos" ),
	new Feast( 10, 11, 10, null, null, null, null, null, "APOSTOLI", "Svätí apoštoli Erast, Olympas, Rodión a spoločníci" ),
	new Feast( 11, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Ménas, Viktor a Vincent" ),
	new Feast( 11, 11, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Teodor Studitský" ),
	new Feast( 12, 11, 10, null, null, null, null, "m", "SVATITEL", "Náš otec svätý Ján Milosrdný, alexandrijský patriarcha" ),
	new Feast( 12, 11, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Níl" ),
	new Feast( 12, 11, 30, null, null, null, null, "ss", "HIEROMUCENIK", "Svätý hieromučeník Jozafát, polocký arcibiskup" ),
	new Feast( 13, 11, 10, null, null, null, null, "ss", "SVATITEL", "Náš otec svätý Ján Zlatoústy, konštantínopolský arcibiskup" ),
	new Feast( 14, 11, 10, null, null, null, null, "s", "APOSTOL", "Svätý a znamenitý apoštol Filip" ),
	new Feast( 15, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci a vyznávači Gurias, Samónas a Habib" ),
	new Feast( 16, 11, 10, null, null, null, null, "s", "APOSTOL", "Svätý apoštol a evanjelista Matúš" ),
	new Feast( 17, 11, 10, null, null, null, null, "m", "SVATITEL", "Náš otec svätý Gregor Divotvorca, neocézarejský biskup" ),
	new Feast( 18, 11, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Platón a Roman" ),
	new Feast( 19, 11, 10, null, null, null, null, null, "PROROK", "Svätý prorok Abdiáš" ),
	new Feast( 19, 11, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Barlaam" ),
	new Feast( 20, 11, 10, null, null, null, 1, null, null, "Blahoslavená sestra Jozafáta" ),
	new Feast( 20, 11, 20, null, null, null, 1, null, "PREPODOBNY", "Náš prepodobný otec Gregor Dekapolita" ),
	new Feast( 20, 11, 30, null, null, null, 1, null, "SVATITEL", "Náš otec svätý Proklos, konštantínopolský arcibiskup" ),
	new Feast( 21, 11, 10, 1, 3, 4, 0, "v", "BOHORODICKA", "Vstup našej presvätého Vládkyne, Bohorodičky Márie, vždy Panny, do chrámu" ),
	new Feast( 22, 11, 10, null, null, null, -1, null, "APOSTOL", "Svätý apoštol Filemon a spoločníci" ),
	new Feast( 23, 11, 10, null, null, null, -2, null, "SVATITELIA", "Naši otcovia svätého Amfilochios, ikonijský biskup, a Gregor, akragantský biskup" ),
	new Feast( 24, 11, 10, null, null, null, -3, "m", "MUCENICA", "Svätá veľkomučenica Katarína" ),
	new Feast( 24, 11, 20, null, null, null, -3, null, "MUCENIK", "Svätý veľkomučeník Merkúr" ),
	new Feast( 25, 11, 10, null, null, null, -4, null, "HIEROMUCENICI", "Naši otcovia, hieromučeníci svätého Kliment, rímsky pápež, a svätého Peter, alexandrijský biskup" ),
	new Feast( 26, 11, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Alypios Stĺpnik" ),
	new Feast( 26, 11, 20, null, null, null, null, "s", null, "Posvätenie chrámu svätého veľkomuč. Juraja, ktorý je v Kyjeve pred bránami svätej Sofie" ),
	new Feast( 27, 11, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Jakub Perzský" ),
	new Feast( 28, 11, 10, null, null, null, null, null, "PREPODOBNOMUCENIK", "Prepodobný mučeník Štefan Nový" ),
	new Feast( 29, 11, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Paramon" ),
	new Feast( 29, 11, 20, null, null, null, null, null, "MUCENIK", "Svätý mučeník Filumen" ),
	new Feast( 30, 11, 10, null, null, null, null, "s", "APOSTOL", "Svätý a znamenitý apoštol Andrej Prvopovolaný" ),
	new Feast( 1, 12, 10, null, null, null, null, null, "PROROK", "Svätý prorok Nahum" ),
	new Feast( 2, 12, 10, null, null, null, null, null, "PROROK", "Svätý prorok Habakuk" ),
	new Feast( 3, 12, 10, null, null, null, null, null, "PROROK", "Svätý prorok Sofoniáš" ),
	new Feast( 4, 12, 10, null, null, null, null, "m", "MUCENICA", "Svätá veľkomučenica Barbora" ),
	new Feast( 4, 12, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Ján Damaský" ),
	new Feast( 5, 12, 10, null, null, null, null, "ss", "PREPODOBNY", "Náš prepodobný a bohonositeľský otec Sáva Posvätený" ),
	new Feast( 6, 12, 10, null, null, null, null, "ss", "SVATITEL", "Náš otec svätý Mikuláš Divotvorca, arcibiskup lykijskej Myry" ),
	new Feast( 7, 12, 10, null, null, null, null, null, "SVATITEL", "Náš otec svätý Ambróz, milánsky biskup" ),
	new Feast( 8, 12, 10, null, null, null, null, "ss", "BOHORODICKA", "Počatie presvätej Bohorodičky svätou Annou" ),
	new Feast( 9, 12, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Patapios" ),
	new Feast( 10, 12, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Ménas, Hermogenés a Eugraf" ),
	new Feast( 11, 12, 10, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Daniel Stĺpnik" ),
	new Feast( 12, 12, 10, null, null, null, null, "m", "PREPODOBNY", "Náš prepodobný otec Spiridon Divotvorca, trimituntský biskup" ),
	new Feast( 13, 12, 10, null, null, null, null, "s", "MUCENICI", "Svätí mučeníci Eustratios, Auxencius, Eugen, Mardarios a Orest" ),
	new Feast( 14, 12, 10, null, null, null, null, null, "MUCENICI", "Svätí mučeníci Tyrsos, Leukios, Filemon, Apollónios a Kallinik" ),
	new Feast( 15, 12, 10, null, null, null, null, null, "HIEROMUCENIK", "Svätý hieromučeník Eleuterios" ),
	new Feast( 15, 12, 20, null, null, null, null, null, "PREPODOBNY", "Náš prepodobný otec Pavol z Latry" ),
	new Feast( 15, 12, 30, null, null, null, null, "ms", "SVATITEL", "Náš otec svätý Štefan Vyznávač, sugdejský arcibiskup" ),
	new Feast( 16, 12, 10, null, null, null, null, null, "PROROK", "Svätý prorok Aggeus" ),
	new Feast( 17, 12, 10, null, null, null, null, "m", "PROROK", "Svätý prorok Daniel a traja svätí mládenci Ananiáš, Azariáš a Mízael" ),
	new Feast( 18, 12, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Sebastián a jeho spoločníci" ),
	new Feast( 19, 12, 10, null, null, null, null, null, "MUCENIK", "Svätý mučeník Bonifác" ),
	new Feast( 20, 12, 10, null, null, null, null, "m", "HIEROMUCENIK", "Svätý hieromučeník Ignác Bohonositeľ" ),
	new Feast( 21, 12, 10, null, null, null, 5, null, "MUCENICA", "Svätá mučenica Juliána" ),
	new Feast( 22, 12, 10, null, null, null, 4, null, "MUCENICA", "Svätá veľkomučenica Anastázia" ),
	new Feast( 23, 12, 10, null, null, null, 3, null, "MUCENICI", "Desiati svätí mučeníci z Kréty" ),
	new Feast( 24, 12, 10, null, null, null, 2, null, "PAN", "Predvečer Narodenia Pána" ),
	new Feast( 24, 12, 20, null, null, null, 1, null, "PAN", "Predvečer Narodenia Pána (so/ne)" ),
	new Feast( 24, 12, 30, null, null, null, 1, null, "PREPODOBNOMUCENICA", "Svätá prepodobná mučenica Eugénia" ),
	new Feast( 25, 12, 10, 5, 5, 6, 0, "v", "PAN", "Narodenie podľa tela nášho Pána, Boha a Spasiteľa Ježiša Krista" ),
	new Feast( 26, 12, 10, null, null, null, -1, "ms", "BOHORODICKA", "Zhromaždenie k presvätej Bohorodičke" ),
	new Feast( 27, 12, 10, null, null, null, -2, "m", "APOSTOL", "Svätý apoštol, prvomučeník a archidiakon Štefan" ),
	new Feast( 27, 12, 20, null, null, null, -2, null, "PREPODOBNY", "Náš prepodobný otec a vyznávač Teodor Popísaný" ),
	new Feast( 28, 12, 10, null, null, null, -3, null, null, "Svätí 20 00 mučeníci upálení v Nikomédii" ),
	new Feast( 29, 12, 10, null, null, null, -4, null, null, "Sväté deti, ktoré dal Herodes povraždiť v Betleheme" ),
	new Feast( 29, 12, 20, null, null, null, -4, null, "PREPODOBNY", "Náš prepodobný otec Marcel" ),
	new Feast( 30, 12, 10, null, null, null, -5, null, "MUCENICA", "Svätá mučenica Anýzia" ),
	new Feast( 31, 12, 10, null, null, null, -6, null, "PREPODOBNA", "Naša prepodobná matka Melánia Rímska" )
];

export function getFeasts(month: number, day: number): Feast[] {
	  return feasts.filter(it => it.day == day && it.month == month);
}

export function getRank(month: number, day: number): string {
    let feasts = getFeasts(month, day);
    let f = feasts[0];
    if (f.rank === "v") {
        if (f.type === "PAN") return "velkyPanov";
        if (f.type === "BOHORODICKA") return "velkyBohorodicny";
        return "velky";
    }
    if (f.rank === "ss") return "sBdenim";
    if (f.rank === "s") return "polyelej";
    if (f.rank === "ms") return "sestricnySVelkymSlavoslovim";
    if (f.rank === "m") return "sestricnySMalymSlavoslovim";
    if (feasts.length > 1) {
        let f2 = feasts[1];
        if (f.rank === null && f2.rank === null) return "dvajaSvati"
    }
    return "jedenSvaty";
}